import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '@/app/context/AuthContext';
import { QuestionsProvider } from '@/app/context/QuestionsContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PathFinder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="absolute inset-0 -z-10 h-full w-full [background:radial-gradient(125%_125%_at_50%_30%,#fff_1%,#7d6655_100%)]">
      <body>
        <QuestionsProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </QuestionsProvider>
      </body>
    </html>
  );
}

