export const howTriggers = [
  "how",
  "how?",
  "how pathfinder",
  "how pathfinder?",
  "how is pathfinder",
  "how is pathfinder?",
  "how does pathfinder work",
  "how does pathfinder work?",
  "how pathfinder works",
  "how pathfinder works?",
  "how to use",
  "how to use?",
  "how to use pf",
  "how to use pf?",
  "how to use pathfinder system",
  "how to use pathfinder system?",
  "how to use the system",
  "how to use the system?",
  "how to use the app",
  "how to use the app?",
  "how to use this",
  "how to use this?",
  "how to use pathfinder app",
  "how to use pathfinder app?",
  "how to use the platform",
  "how to use the platform?",
  "how to use pathfinder",
  "how to use pathfinder?",
  "how to use this system",
  "how to use this system?",
  "how to use this app",
  "how to use this app?",
  "how do I use pathfinder",
  "how do I use pathfinder?",
  "how can I use pathfinder",
  "how can I use pathfinder?",
  "how does this system work",
  "how does this system work?",
  "how does the pathfinder system work",
  "how does the pathfinder system work?",
  "how do I start pathfinder",
  "how do I start pathfinder?",
  "how do I begin using pathfinder",
  "how do I begin using pathfinder?",
  "how does pathfinder operate",
  "how does pathfinder operate?",
  "how pathfinder operate",
  "how pathfinder operate?",
  "how do I make this work",
  "how do I make this work?",
  "how does this work",
  "how does this work?",
  "how it works",
  "how it works?",
  "how does it work",
  "how does it work?",
  "how to start using pathfinder",
  "how to start using pathfinder?",
  "how to navigate pathfinder",
  "how to navigate pathfinder?",
  "how to use the pathfinder system",
  "how to use the pathfinder system?",
  "how does the pathfinder app work",
  "how does the pathfinder app work?",
  "how does the pathfinder platform work",
  "how does the pathfinder platform work?",
  "how to setup pathfinder",
  "how to setup pathfinder?",
  "how do I access pathfinder",
  "how do I access pathfinder?",
  "how do I use this thing",
  "how do I use this thing?",
  "how do I use this feature",
  "how do I use this feature?",
  "how does this feature work",
  "how does this feature work?",
  "how do I get started",
  "how do I get started?",
  "how can I get started",
  "how can I get started?",
  "how does pathfinder function",
  "how does pathfinder function?",
  "how does the system function",
  "how does the system function?",
  "how am I supposed to use pathfinder",
  "how am I supposed to use pathfinder?",
  "how should I use pathfinder",
  "how should I use pathfinder?",
  "how do I work pathfinder",
  "how do I work pathfinder?",
  "how do you use pathfinder",
  "how do you use pathfinder?",
  "how tf does this work",
  "how tf does this work?",
  "how to properly use pathfinder",
  "how to properly use pathfinder?",
  "how does one use pathfinder",
  "how does one use pathfinder?",
  "how do I operate pathfinder",
  "how do I operate pathfinder?",
  "how do you operate pathfinder",
  "how do you operate pathfinder?",
  "how do I run pathfinder",
  "how do I run pathfinder?",
  "how do I use pf",
  "how do I use pf?",
  "how pf works",
  "how pf works?",
  "pf how",
  "pf how?"
];
