export const whatTriggers = [
  "what",
  "what?",
  "what can you do?",
  "what can you do",
  "what is this",
  "what is this?",
  "what pathfinder",
  "what pathfinder?",
  "what is pathfinder",
  "what is pathfinder?",
  "what's pathfinder",
  "what's pathfinder?",
  "whats pathfinder",
  "whats pathfinder?",
  "what is a pathfinder",
  "what is a pathfinder?",
  "what does pathfinder mean",
  "what does pathfinder mean?",
  "what does pathfinder do",
  "what does pathfinder do?",
  "what is pathfinder about",
  "what is pathfinder about?",
  "what is about pathfinder",
  "what is about pathfinder?",
  "about pathfinder",
  "about pathfinder?",
  "pathfinder?",
  "pathfinder",
  "pathfinder ???",
  "what even is pathfinder",
  "what even is pathfinder?",
  "what actually is pathfinder",
  "what actually is pathfinder?",
  "what is this pathfinder",
  "what is this pathfinder?",
  "what is that pathfinder",
  "what is that pathfinder?",
  "what is the pathfinder system",
  "what is the pathfinder system?",
  "what is the pathfinder app",
  "what is the pathfinder app?",
  "what is the pathfinder project",
  "what is the pathfinder project?",
  "what is pathfinder for",
  "what is pathfinder for?",
  "what is pathfinder used for",
  "what is pathfinder used for?",
  "what pathfinder do",
  "what pathfinder do?",
  "what does pathfinder help with",
  "what does pathfinder help with?",
  "what is pathfinder supposed to be",
  "what is pathfinder supposed to be?",
  "explain pathfinder",
  "explain pathfinder?",
  "pathfinder explanation",
  "pathfinder explanation?",
  "pathfinder what",
  "pathfinder what?",
  "what pathfinder means",
  "what pathfinder means?",
  "what can you say about pathfinder",
  "what can you say about pathfinder?",
  "what is pathfinder all about",
  "what is pathfinder all about?",
  "tell me about pathfinder",
  "tell me about pathfinder?",
  "describe pathfinder",
  "describe pathfinder?",
  "pathfinder info",
  "pathfinder info?",
  "info about pathfinder",
  "info about pathfinder?",
  "what does the pathfinder system do",
  "what does the pathfinder system do?",
  "what is the purpose of pathfinder",
  "what is the purpose of pathfinder?",
  "purpose of pathfinder",
  "purpose of pathfinder?",
  "pathfinder what is it",
  "pathfinder what is it?",
  "what is pathfinder exactly",
  "what is pathfinder exactly?",
  "so what is pathfinder",
  "so what is pathfinder?",
  "uhh what is pathfinder",
  "uhh what is pathfinder?",
  "explain what pathfinder is",
  "explain what pathfinder is?",
  "what do you mean by pathfinder",
  "what do you mean by pathfinder?",
  "what is this pathfinder thing",
  "what is this pathfinder thing?",
  "what is the meaning of pathfinder",
  "what is the meaning of pathfinder?",
  "pathfinder meaning",
  "pathfinder meaning?",
  "what kind of app is pathfinder",
  "what kind of app is pathfinder?",
  "what is pathfinder used for",
  "what is pathfinder used for?",
  "what is the function of pathfinder",
  "what is the function of pathfinder?",
  "what does pathfinder provide",
  "what does pathfinder provide?",
  "pathfinder?",
  "what is pf?",
  "pf meaning",
  "pf meaning?",
  "what is pf",
  "what is pf?",
  "What is this system",
"What is this system?",
"What is this system about",
"What is this system about?",
"What is this about",
"What is this about?",
"What is this app about",
"What is this app about?",
"What is this platform about",
"What is this platform about?",
"What is this website about",
"What is this website about?",
"What is this for",
"What is this for?",
"what is this thing",
"what is this thing?",
"what is this system used for",
"what is this system used for?",
"what does this system do",
"what does this system do?",
"what does this app do",
"what does this app do?",
"what is this pf",
"what is this pf?",
"pf what",
"pf what?",
"what is this application",
"what is this application?",
"what even is this system",
"what even is this system?",
"what even is this",
"what even is this?",
];
