export const whoTriggers = [
  "who",
  "who?",
  "who pathfinder",
  "who pathfinder?",
  "who behind pathfinder",
  "who behind pathfinder?",
  "who is behind pathfinder",
  "who is behind pathfinder?",
  "who made pathfinder",
  "who made pathfinder?",
  "who created pathfinder",
  "who created pathfinder?",
  "who invented pathfinder",
  "who invented pathfinder?",
  "who designed pathfinder",
  "who designed pathfinder?",
  "who built pathfinder",
  "who built pathfinder?",
  "who build pathfinder",
    "who build pathfinder?",
  "who developed pathfinder",
  "who developed pathfinder?",
  "who worked on pathfinder",
  "who worked on pathfinder?",
  "who contributed to pathfinder",
  "who contributed to pathfinder?",
  "who is involved in pathfinder",
  "who is involved in pathfinder?",
  "who are the developers of pathfinder",
  "who are the developers of pathfinder?",
  "who are the creators of pathfinder",
  "who are the creators of pathfinder?",
  "who are the people behind pathfinder",
  "who are the people behind pathfinder?",
  "who are the team behind pathfinder",
  "who are the team behind pathfinder?",
  "who runs pathfinder",
  "who runs pathfinder?",
  "who manages pathfinder",
  "who manages pathfinder?",
  "who operates pathfinder",
  "who operates pathfinder?",
  "who is responsible for pathfinder",
  "who is responsible for pathfinder?",
  "who’s behind pathfinder",
  "who’s behind pathfinder?",
  "whos behind pathfinder",
  "whos behind pathfinder?",
  "who made the pathfinder app",
  "who made the pathfinder app?",
  "who created the pathfinder app",
  "who created the pathfinder app?",
  "who developed the pathfinder app",
  "who developed the pathfinder app?",
  "who is the creator of pathfinder",
  "who is the creator of pathfinder?",
  "who is the developer of pathfinder",
  "who is the developer of pathfinder?",
  "who started pathfinder",
  "who started pathfinder?",
  "who founded pathfinder",
  "who founded pathfinder?",
  "who is the founder of pathfinder",
  "who is the founder of pathfinder?",
  "who makes pathfinder",
  "who makes pathfinder?",
  "who are the makers of pathfinder",
  "who are the makers of pathfinder?",
  "who coded pathfinder",
  "who coded pathfinder?",
  "who wrote pathfinder",
  "who wrote pathfinder?",
  "who programmed pathfinder",
  "who programmed pathfinder?",
  "who owns pathfinder",
  "who owns pathfinder?",
  "who runs the pathfinder system",
  "who runs the pathfinder system?",
  "who is the team of pathfinder",
  "who is the team of pathfinder?",
  "who is behind the pathfinder website",
  "who is behind the pathfinder website?",
  "who built the pathfinder website",
  "who built the pathfinder website?",
  "who developed the pathfinder website",
  "who developed the pathfinder website?",
  "pathfinder who made it",
  "pathfinder who made it?",
  "pathfinder who created it",
  "pathfinder who created it?",
  "pathfinder creators",
  "pathfinder creators?",
  "pathfinder developers",
  "pathfinder developers?",
  "pathfinder devs",
  "pathfinder devs?",
  "pathfinder team",
  "pathfinder team?",
  "team behind pathfinder",
  "team behind pathfinder?",
  "who is in charge of pathfinder",
  "who is in charge of pathfinder?",
  "who oversees pathfinder",
  "who oversees pathfinder?",
  "who is responsible for the pathfinder project",
  "who is responsible for the pathfinder project?",
  "who handles pathfinder",
  "who handles pathfinder?",
  "who supports pathfinder",
  "who supports pathfinder?",
  "who maintains pathfinder",
  "who maintains pathfinder?",
  "who produced pathfinder",
  "who produced pathfinder?",
  "who made pathfinder game",
  "who made pathfinder game?",
  "who is the pathfinder dev",
  "who is the pathfinder dev?",
  "who is the pathfinder creator",
  "who is the pathfinder creator?",
  "who made pathfinder system",
  "who made pathfinder system?",
  "who is working on pathfinder",
  "who is working on pathfinder?",
  "who built the pathfinder project",
  "who built the pathfinder project?",
  "who are behind pathfinder",
  "who are behind pathfinder?",
  "who make pathfinder?",
  "who make pathfinder",
  "who did pathfinder",
  "who did pathfinder?",
  "who created this pathfinder",
  "who created this pathfinder?",
  "who developed this pathfinder",
  "who developed this pathfinder?",
  "who is the owner of pathfinder",
  "who is the owner of pathfinder?",
  "who is the group behind pathfinder",
  "who is the group behind pathfinder?",
  "who is the team responsible for pathfinder",
  "who is the team responsible for pathfinder?",
  "who is the pathfinder team made of",
  "who is the pathfinder team made of?",
  "who is behind the pathfinder platform",
  "who is behind the pathfinder platform?",
  "who are the engineers of pathfinder",
  "who are the engineers of pathfinder?",
  "who designed the pathfinder system",
  "who designed the pathfinder system?",
  "who are the programmers of pathfinder",
  "who are the programmers of pathfinder?",
  "who are the creators of the pathfinder system",
  "who are the creators of the pathfinder system?",
  "who is creating pathfinder",
  "who is creating pathfinder?",
  "who was involved in creating pathfinder",
  "who was involved in creating pathfinder?",
  "who is behind the scenes of pathfinder",
  "who is behind the scenes of pathfinder?"
];
