export const whyTriggers = [
"why",
  "why?",
  "why pathfinder",
  "why pathfinder?",
  "why use pathfinder",
  "why use pathfinder?",
  "why should i use pathfinder",
  "why should i use pathfinder?",
  "why do i need pathfinder",
  "why do i need pathfinder?",
  "why pathfinder app",
  "why pathfinder app?",
  "why choose pathfinder",
  "why choose pathfinder?",
  "why would i use pathfinder",
  "why would i use pathfinder?",
  "why do people use pathfinder",
  "why do people use pathfinder?",
  "why is pathfinder important",
  "why is pathfinder important?",
  "why is pathfinder needed",
  "why is pathfinder needed?",
  "why is pathfinder used",
  "why is pathfinder used?",
  "why do we need pathfinder",
  "why do we need pathfinder?",
  "why did you create pathfinder",
  "why did you create pathfinder?",
  "why was pathfinder created",
  "why was pathfinder created?",
  "why make pathfinder",
  "why make pathfinder?",
  "why is there pathfinder",
  "why is there pathfinder?",
  "why this pathfinder",
  "why this pathfinder?",
  "why did you make pathfinder",
  "why did you make pathfinder?",
  "why does pathfinder exist",
  "why does pathfinder exist?",
  "why do i have pathfinder",
  "why do i have pathfinder?",
  "why even pathfinder",
  "why even pathfinder?",
  "why would anyone use pathfinder",
  "why would anyone use pathfinder?",
  "why should anyone use pathfinder",
  "why should anyone use pathfinder?",
  "why am i using pathfinder",
  "why am i using pathfinder?",
  "why choose this system",
  "why choose this system?",
  "why pick pathfinder",
  "why pick pathfinder?",
  "why pathfinder tho",
  "why pathfinder tho?",
  "why pathfinder though",
  "why pathfinder though?",
  "why u made pathfinder",
  "why u made pathfinder?",
  "why did u make pathfinder",
  "why did u make pathfinder?",
  "why do i need this",
  "why do i need this?",
  "why this system",
  "why this system?",
  
  /* === Added expansions === */
  "why is pathfinder",
  "why is pathfinder?",
  "why is pathfinder like this",
  "why is pathfinder like this?",
  "why is pathfinder created",
  "why is pathfinder created?",
  "why is pathfinder made",
  "why is pathfinder made?",
  "why is pathfinder a thing",
  "why is pathfinder a thing?",
  "why is pathfinder even a thing",
  "why is pathfinder even a thing?",
  "why is pathfinder built",
  "why is pathfinder built?",
  "why pathfinder exists",
  "why pathfinder exists?",
  "why does this exist",
  "why does this exist?",
  "why does this system exist",
  "why does this system exist?",
  "why do i need this system",
  "why do i need this system?",
  "why is this system here",
  "why is this system here?",
  "why is this app here",
  "why is this app here?",
  
  /* casual/slang/misspellings */
  "why dis pathfinder",
  "why dis pathfinder?",
  "why pathfnder",
  "why pathfnder?",
  "why path finder",
  "why path finder?"];
